[dest]
rpc = ""

[dest.lz]
endpoint = ""
eid = 

[dest.usdc]
proxy = ""
masterMinter = ""
masterMinterOwner = ""

[dest.usdc.bridge.init]
owner = ""
proxyAdminOwner = ""

[dest.usdc.bridge.deployment]
proxy = ""

[dest.usdt.init]
owner = ""
proxyAdminOwner = ""
name = "Bridged USDT (Citrea)"
symbol = "USDT.e"

[dest.usdt.deployment]
proxy = ""

[dest.usdt.bridge.init]
owner = ""
proxyAdminOwner = ""

[dest.usdt.bridge.deployment]
proxy = ""

[src]
rpc = ""

[src.lz]
endpoint = ""
eid =

[src.usdc]
proxy = ""

[src.usdc.bridge.init]
owner = ""
proxyAdminOwner = ""

[src.usdc.bridge.deployment]
proxy = ""

[src.usdt]
contract = ""

[src.usdt.bridge.init]
owner = ""
proxyAdminOwner = ""

[src.usdt.bridge.deployment]
proxy = ""