[dest]
rpc = ""
verifier = ""
verifierUrl = ""

[dest.lz]
endpoint = ""
eid = 

[dest.lz.send]
ulnLib = ""
confirmations = 
requiredDVNCount = 
optionalDVNCount = 
optionalDVNThreshold = 
requiredDVNs = []
optionalDVNs = []

[dest.lz.recv]
ulnLib = ""
gracePeriod = 
confirmations = 
requiredDVNCount = 
optionalDVNCount = 
optionalDVNThreshold = 
requiredDVNs = []
optionalDVNs = []

[dest.lz.options]
receiveGas = 

[dest.usdc.init]
owner = ""
proxyAdmin = ""
masterMinterOwner = ""
name = "Bridged USDC (Citrea)"
symbol = "USDC.e"

[dest.usdc.deployment]
proxy = ""
masterMinter = ""

[dest.usdc.bridge.init]
owner = ""
proxyAdminOwner = ""

[dest.usdc.bridge.deployment]
proxy = ""

[dest.usdt.init]
owner = ""
proxyAdminOwner = ""
name = "Bridged USDT (Citrea)"
symbol = "USDT.e"

[dest.usdt.deployment]
proxy = ""

[dest.usdt.bridge.init]
owner = ""
proxyAdminOwner = ""

[dest.usdt.bridge.deployment]
proxy = ""

[src]
rpc = ""
verifier = ""
verifierUrl = ""

[src.lz]
endpoint = ""
eid = 

[src.lz.send]
ulnLib = ""
confirmations = 
requiredDVNCount = 
optionalDVNCount = 
optionalDVNThreshold = 
requiredDVNs = []
optionalDVNs = []

[src.lz.recv]
ulnLib = ""
gracePeriod = 
confirmations = 
requiredDVNCount = 
optionalDVNCount = 
optionalDVNThreshold = 
requiredDVNs = []
optionalDVNs = []

[src.lz.options]
receiveGas = 

[src.usdc]
proxy = ""

[src.usdc.bridge.init]
owner = ""
proxyAdminOwner = ""

[src.usdc.bridge.deployment]
proxy = ""

[src.usdt]
contract = ""

[src.usdt.bridge.init]
owner = ""
proxyAdminOwner = ""

[src.usdt.bridge.deployment]
proxy = ""
