[dest]
rpc = "https://rpc.mainnet.citrea.xyz"

    [dest.lz]
    endpoint = ""
    eid =

    [dest.usdc]
    proxy = ""
    masterMinter = ""

        [dest.usdc.bridge]

        [dest.usdc.bridge.init]
        owner = ""
        proxyAdminOwner = ""
        
        [dest.usdc.bridge.deployment]
        proxyAdmin = ""
        implementation = ""
        proxy = ""

    [dest.usdt]

    [dest.usdt.init]
    owner = ""
    proxyAdminOwner = ""
    name = "Bridged USDT (Citrea)"
    symbol = "USDT.e"

    [dest.usdt.deployment]
    proxy = ""
    # Also used for bridge
    proxyAdmin = ""

        [dest.usdt.bridge]

        [dest.usdt.bridge.init]
        owner = ""

        [dest.usdt.bridge.deployment]
        implementation = ""
        proxy = ""
        
[src]
rpc = "https://eth.drpc.org"

    [src.lz]
    endpoint = "0x1a44076050125825900e736c501f859c50fE728c"
    eid = 30101

    [src.usdc]
    proxy = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

        [src.usdc.bridge]

        [src.usdc.bridge.init]
        owner = ""
        proxyAdminOwner = ""
        
        [src.usdc.bridge.deployment]
        proxyAdmin = ""
        implementation = ""
        proxy = ""

    [src.usdt]
    contract = "0xdAC17F958D2ee523a2206206994597C13D831ec7"

        [src.usdt.bridge]

        [src.usdt.bridge.init]
        owner = ""
        proxyAdminOwner = ""

        [src.usdt.bridge.deployment]
        proxyAdmin = ""
        implementation = ""
        proxy = ""