[dest]
rpc = "https://rpc.testnet.citrea.xyz"

[dest.lz]
endpoint = "0x6C7Ab2202C98C4227C5c46f1417D81144DA716Ff"
eid = 40344

[dest.usdc.init]
owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
proxyAdmin = "0x69646c37092166B89E880e38f6F345c5d4B3b99B"
masterMinterOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
name = "Bridged USDC (Citrea)"
symbol = "USDC.e"

[dest.usdc.deployment]
proxy = ""
masterMinter = ""

[dest.usdc.bridge.init]
owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

[dest.usdc.bridge.deployment]
proxy = ""

[dest.usdt.init]
owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
name = "Bridged USDT (Citrea)"
symbol = "USDT.e"

[dest.usdt.deployment]
proxy = ""

[dest.usdt.bridge.init]
owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

[dest.usdt.bridge.deployment]
proxy = ""

[src]
rpc = "https://sepolia.drpc.org"

[src.lz]
endpoint = "0x6EDCE65403992e310A62460808c4b910D972f10f"
eid = 40161

[src.usdc]
proxy = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"

[src.usdc.bridge.init]
owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

[src.usdc.bridge.deployment]
proxy = ""

[src.usdt]
contract = "0x7169D38820dfd117C3FA1f22a697dBA58d90BA06"

[src.usdt.bridge.init]
owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

[src.usdt.bridge.deployment]
proxy = ""
