[citrea]
rpc = "https://rpc.testnet.citrea.xyz"

    [citrea.lz]
    endpoint = "0x6C7Ab2202C98C4227C5c46f1417D81144DA716Ff"
    eid = 40344

    [citrea.usdc]
    proxy = "0x6B6c02bF1f957f2D5a673e06fCE93F09d933Af02"
    masterMinter = "0xcF531Bc0c45D4712AE9eCDF2B527527996B4a0E2"

        [citrea.usdc.bridge]

        [citrea.usdc.bridge.init]
        owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
        proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
        
        [citrea.usdc.bridge.deployment]
        implementation = "0x66Da90f71fCd46f6c37dC97fa46Cf64918fFE232"
        proxy = "0x8851610c31789EAB415E34A21187DD25a1f3649d"

    [citrea.usdt]

    [citrea.usdt.init]
    owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
    proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

    [citrea.usdt.deployment]
    proxy = "0x9aA4D65Df8BD3693e491ff163E18DffB86ba7e0e"

        [citrea.usdt.bridge]

        [citrea.usdt.bridge.init]
        owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
        proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

        [citrea.usdt.bridge.deployment]
        implementation = "0x6ECa384f6dffdF396c93354e7f3d341eb3f96eEA"
        proxy = "0x22924fECF57936C905B60B44082eF8DED86d0B31"
        
[eth]
rpc = "https://sepolia.drpc.org"

    [eth.lz]
    endpoint = "0x6EDCE65403992e310A62460808c4b910D972f10f"
    eid = 40161

    [eth.usdc]
    proxy = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"

        [eth.usdc.bridge]

        [eth.usdc.bridge.init]
        owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
        proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
        
        [eth.usdc.bridge.deployment]
        implementation = "0x07091D66538755ef9718A736Ac4864BadC0a27eb"
        proxy = "0xB3602CC0Cb4380C9a7A922a7Ddf6F6Ad97442565"

    [eth.usdt]
    contract = "0x7169D38820dfd117C3FA1f22a697dBA58d90BA06"

        [eth.usdt.bridge]

        [eth.usdt.bridge.init]
        owner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"
        proxyAdminOwner = "0xDc94F4e8F84180C1E807fC4d6b43d65cb459b510"

        [eth.usdt.bridge.deployment]
        implementation = "0x46A6E5472D68A987693cE6FB353C358d7ACa7dAD"
        proxy = "0xF92e6A50F3AAFA0d0dfCD1C31166D90A1AbCd905"